// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreOde.Models;

#nullable disable

namespace StoreOde.Migrations
{
    [DbContext(typeof(SouqcomContext))]
    [Migration("20260809105721_SeedProductCategories")]
    partial class SeedProductCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StoreOde.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UX_Cart_UserId_ProductId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("StoreOde.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassFilter")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Top sports brand",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Premium sportswear",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Comfort & style",
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fitness focused",
                            Name = "Reebok"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Performance gear",
                            Name = "Under Armour"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Running excellence",
                            Name = "New Balance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Classic sportswear",
                            Name = "Champion"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Retro sports fashion",
                            Name = "Fila"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Professional running gear",
                            Name = "Asics"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Italian sports style",
                            Name = "Lotto"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Football heritage brand",
                            Name = "Umbro"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Sport & lifestyle wear",
                            Name = "Diadora"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Street sports fashion",
                            Name = "Kappa"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Outdoor & adventure gear",
                            Name = "Columbia"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Extreme weather performance",
                            Name = "The North Face"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Products without a specified brand",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("StoreOde.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("ContactMessage", (string)null);
                });

            modelBuilder.Entity("StoreOde.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Catid")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Priceafterdiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("priceafterdiscount");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("ReviewUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Catid");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Catid = 1,
                            Name = "Nike Hoodie Black",
                            Price = 1200m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 2,
                            Catid = 2,
                            Name = "Adidas Running Shoes",
                            Price = 2000m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 3,
                            Catid = 16,
                            Name = "Sport Shorts Blue",
                            Price = 500m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 4,
                            Catid = 16,
                            Name = "Winter Jacket Premium",
                            Price = 1500m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 5,
                            Catid = 16,
                            Name = "Slim Fit Pants",
                            Price = 900m,
                            Quantity = 20,
                            Type = "pants"
                        },
                        new
                        {
                            Id = 6,
                            Catid = 16,
                            Name = "Classic White Hoodie",
                            Price = 1100m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 7,
                            Catid = 16,
                            Name = "Air Max Sneakers",
                            Price = 2500m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 8,
                            Catid = 16,
                            Name = "Gym Shorts Grey",
                            Price = 450m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 9,
                            Catid = 16,
                            Name = "Leather Jacket Black",
                            Price = 3000m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 10,
                            Catid = 16,
                            Name = "Jogger Pants",
                            Price = 800m,
                            Quantity = 20,
                            Type = "pants"
                        },
                        new
                        {
                            Id = 11,
                            Catid = 16,
                            Name = "Oversized Hoodie Red",
                            Price = 1300m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 12,
                            Catid = 2,
                            Name = "Adidas Ultra Boost",
                            Price = 2800m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 13,
                            Catid = 16,
                            Name = "Training Shorts",
                            Price = 550m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 14,
                            Catid = 16,
                            Name = "Denim Jacket",
                            Price = 1700m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 15,
                            Catid = 16,
                            Name = "Cargo Pants",
                            Price = 1000m,
                            Quantity = 20,
                            Type = "pants"
                        },
                        new
                        {
                            Id = 16,
                            Catid = 16,
                            Name = "Street Hoodie Grey",
                            Price = 1250m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 17,
                            Catid = 1,
                            Name = "Nike Air Force",
                            Price = 2600m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 18,
                            Catid = 16,
                            Name = "Summer Shorts",
                            Price = 400m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 19,
                            Catid = 16,
                            Name = "Windbreaker Jacket",
                            Price = 1400m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 20,
                            Catid = 16,
                            Name = "Sport Jogger",
                            Price = 850m,
                            Quantity = 20,
                            Type = "pants"
                        },
                        new
                        {
                            Id = 21,
                            Catid = 16,
                            Name = "Hoodie Zip Black",
                            Price = 1350m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 22,
                            Catid = 16,
                            Name = "Running Shoes Pro",
                            Price = 2200m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 23,
                            Catid = 16,
                            Name = "Fitness Shorts",
                            Price = 480m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 24,
                            Catid = 16,
                            Name = "Puffer Jacket",
                            Price = 3200m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 25,
                            Catid = 16,
                            Name = "Casual Pants Beige",
                            Price = 950m,
                            Quantity = 20,
                            Type = "pants"
                        },
                        new
                        {
                            Id = 26,
                            Catid = 16,
                            Name = "Tech Hoodie Blue",
                            Price = 1450m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 27,
                            Catid = 1,
                            Name = "Nike Zoom Shoes",
                            Price = 2400m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 28,
                            Catid = 16,
                            Name = "Sport Shorts Black",
                            Price = 520m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 29,
                            Catid = 16,
                            Name = "Bomber Jacket",
                            Price = 1800m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 30,
                            Catid = 16,
                            Name = "Slim Jogger Grey",
                            Price = 870m,
                            Quantity = 20,
                            Type = "pants"
                        },
                        new
                        {
                            Id = 31,
                            Catid = 16,
                            Name = "Hoodie Oversize White",
                            Price = 1500m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 32,
                            Catid = 2,
                            Name = "Adidas Originals Shoes",
                            Price = 2700m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 33,
                            Catid = 16,
                            Name = "Running Shorts Green",
                            Price = 460m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 34,
                            Catid = 16,
                            Name = "Winter Coat Long",
                            Price = 3500m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 35,
                            Catid = 16,
                            Name = "Track Pants Black",
                            Price = 920m,
                            Quantity = 20,
                            Type = "pants"
                        },
                        new
                        {
                            Id = 36,
                            Catid = 16,
                            Name = "Streetwear Hoodie",
                            Price = 1600m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 37,
                            Catid = 1,
                            Name = "Nike Casual Shoes",
                            Price = 2300m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 38,
                            Catid = 16,
                            Name = "Gym Shorts Red",
                            Price = 500m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 39,
                            Catid = 16,
                            Name = "Rain Jacket",
                            Price = 1900m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 40,
                            Catid = 16,
                            Name = "Cotton Pants",
                            Price = 780m,
                            Quantity = 20,
                            Type = "pants"
                        },
                        new
                        {
                            Id = 41,
                            Catid = 16,
                            Name = "Basic Hoodie Grey",
                            Price = 1000m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 42,
                            Catid = 16,
                            Name = "Sport Shoes Lite",
                            Price = 2100m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 43,
                            Catid = 16,
                            Name = "Training Shorts Pro",
                            Price = 530m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 44,
                            Catid = 16,
                            Name = "Leather Coat",
                            Price = 4000m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 45,
                            Catid = 16,
                            Name = "Relax Pants",
                            Price = 820m,
                            Quantity = 20,
                            Type = "pants"
                        },
                        new
                        {
                            Id = 46,
                            Catid = 16,
                            Name = "Urban Hoodie",
                            Price = 1400m,
                            Quantity = 20,
                            Type = "hoodie"
                        },
                        new
                        {
                            Id = 47,
                            Catid = 16,
                            Name = "Running Sneakers Elite",
                            Price = 3000m,
                            Quantity = 20,
                            Type = "shoes"
                        },
                        new
                        {
                            Id = 48,
                            Catid = 16,
                            Name = "Sport Shorts Pro",
                            Price = 600m,
                            Quantity = 20,
                            Type = "shorts"
                        },
                        new
                        {
                            Id = 49,
                            Catid = 16,
                            Name = "Parka Jacket",
                            Price = 3800m,
                            Quantity = 20,
                            Type = "jacket"
                        },
                        new
                        {
                            Id = 50,
                            Catid = 16,
                            Name = "Cargo Jogger Pants",
                            Price = 1100m,
                            Quantity = 20,
                            Type = "pants"
                        });
                });

            modelBuilder.Entity("StoreOde.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("StoreOde.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Review", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Amazing quality and fast delivery!",
                            Email = "ahmed@gmail.com",
                            Name = "Ahmed Hassan"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Original products and great prices.",
                            Email = "sara@gmail.com",
                            Name = "Sara Mohamed"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Very comfortable and high quality.",
                            Email = "omar@gmail.com",
                            Name = "Omar Ali"
                        },
                        new
                        {
                            Id = 4,
                            Description = "I loved the hoodie, perfect fit!",
                            Email = "mona@gmail.com",
                            Name = "Mona Adel"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fast delivery and excellent service.",
                            Email = "khaled@gmail.com",
                            Name = "Khaled Mostafa"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Products are exactly as shown in pictures.",
                            Email = "nour@gmail.com",
                            Name = "Nour Ahmed"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Very comfortable shoes, highly recommended.",
                            Email = "youssef@gmail.com",
                            Name = "Youssef Ali"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Great quality and affordable prices.",
                            Email = "salma@gmail.com",
                            Name = "Salma Tarek"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Best sportswear store I’ve tried.",
                            Email = "mohamed@gmail.com",
                            Name = "Mohamed Gamal"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Amazing experience, will buy again.",
                            Email = "heba@gmail.com",
                            Name = "Heba Mostafa"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreOde.Models.Cart", b =>
                {
                    b.HasOne("StoreOde.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Cart_Product");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cart_AspNetUsers_UserId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreOde.Models.Product", b =>
                {
                    b.HasOne("StoreOde.Models.Category", "Cat")
                        .WithMany("Products")
                        .HasForeignKey("Catid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Product_Category");

                    b.Navigation("Cat");
                });

            modelBuilder.Entity("StoreOde.Models.ProductImage", b =>
                {
                    b.HasOne("StoreOde.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ProductImages_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreOde.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StoreOde.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
